/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyTokenRouteImport } from './routes/verify.$token'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as ApiAuthSignoutRouteImport } from './routes/api/auth/signout'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthDiscordGuildsRouteImport } from './routes/api/auth/discord-guilds'
import { Route as ApiAuthDiscordRouteImport } from './routes/api/auth/discord'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as AuthenticatedDashboardBillingRouteImport } from './routes/_authenticated/dashboard.billing'
import { Route as AuthenticatedDashboardServersIndexRouteImport } from './routes/_authenticated/dashboard.servers.index'
import { Route as ApiPublicVerifyTokenRouteImport } from './routes/api/public/verify.$token'
import { Route as ApiPublicBotBackupRouteImport } from './routes/api/public/bot/backup'
import { Route as ApiBotStatusGuildIdRouteImport } from './routes/api/bot/status.$guildId'
import { Route as AuthenticatedDashboardServersGuildIdRouteImport } from './routes/_authenticated/dashboard.servers.$guildId'
import { Route as ApiPublicBotVerifiedMembersGuildIdRouteImport } from './routes/api/public/bot/verified-members.$guildId'
import { Route as ApiPublicBotConfigGuildIdRouteImport } from './routes/api/public/bot/config.$guildId'
import { Route as ApiBotGuildsGuildIdConfigRouteImport } from './routes/api/bot/guilds.$guildId.config'
import { Route as ApiBotGuildsGuildIdBackupsRouteImport } from './routes/api/bot/guilds.$guildId.backups'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiAuthSignoutRoute = ApiAuthSignoutRouteImport.update({
  id: '/api/auth/signout',
  path: '/api/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordGuildsRoute = ApiAuthDiscordGuildsRouteImport.update({
  id: '/api/auth/discord-guilds',
  path: '/api/auth/discord-guilds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordRoute = ApiAuthDiscordRouteImport.update({
  id: '/api/auth/discord',
  path: '/api/auth/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardBillingRoute =
  AuthenticatedDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardServersIndexRoute =
  AuthenticatedDashboardServersIndexRouteImport.update({
    id: '/servers/',
    path: '/servers/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicVerifyTokenRoute = ApiPublicVerifyTokenRouteImport.update({
  id: '/api/public/verify/$token',
  path: '/api/public/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotBackupRoute = ApiPublicBotBackupRouteImport.update({
  id: '/api/public/bot/backup',
  path: '/api/public/bot/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotStatusGuildIdRoute = ApiBotStatusGuildIdRouteImport.update({
  id: '/api/bot/status/$guildId',
  path: '/api/bot/status/$guildId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardServersGuildIdRoute =
  AuthenticatedDashboardServersGuildIdRouteImport.update({
    id: '/servers/$guildId',
    path: '/servers/$guildId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicBotVerifiedMembersGuildIdRoute =
  ApiPublicBotVerifiedMembersGuildIdRouteImport.update({
    id: '/api/public/bot/verified-members/$guildId',
    path: '/api/public/bot/verified-members/$guildId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBotConfigGuildIdRoute =
  ApiPublicBotConfigGuildIdRouteImport.update({
    id: '/api/public/bot/config/$guildId',
    path: '/api/public/bot/config/$guildId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBotGuildsGuildIdConfigRoute =
  ApiBotGuildsGuildIdConfigRouteImport.update({
    id: '/api/bot/guilds/$guildId/config',
    path: '/api/bot/guilds/$guildId/config',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBotGuildsGuildIdBackupsRoute =
  ApiBotGuildsGuildIdBackupsRouteImport.update({
    id: '/api/bot/guilds/$guildId/backups',
    path: '/api/bot/guilds/$guildId/backups',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/legal': typeof LegalRoute
  '/pricing': typeof PricingRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/discord': typeof ApiAuthDiscordRoute
  '/api/auth/discord-guilds': typeof ApiAuthDiscordGuildsRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/servers/$guildId': typeof AuthenticatedDashboardServersGuildIdRoute
  '/api/bot/status/$guildId': typeof ApiBotStatusGuildIdRoute
  '/api/public/bot/backup': typeof ApiPublicBotBackupRoute
  '/api/public/verify/$token': typeof ApiPublicVerifyTokenRoute
  '/dashboard/servers/': typeof AuthenticatedDashboardServersIndexRoute
  '/api/bot/guilds/$guildId/backups': typeof ApiBotGuildsGuildIdBackupsRoute
  '/api/bot/guilds/$guildId/config': typeof ApiBotGuildsGuildIdConfigRoute
  '/api/public/bot/config/$guildId': typeof ApiPublicBotConfigGuildIdRoute
  '/api/public/bot/verified-members/$guildId': typeof ApiPublicBotVerifiedMembersGuildIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/legal': typeof LegalRoute
  '/pricing': typeof PricingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/discord': typeof ApiAuthDiscordRoute
  '/api/auth/discord-guilds': typeof ApiAuthDiscordGuildsRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/servers/$guildId': typeof AuthenticatedDashboardServersGuildIdRoute
  '/api/bot/status/$guildId': typeof ApiBotStatusGuildIdRoute
  '/api/public/bot/backup': typeof ApiPublicBotBackupRoute
  '/api/public/verify/$token': typeof ApiPublicVerifyTokenRoute
  '/dashboard/servers': typeof AuthenticatedDashboardServersIndexRoute
  '/api/bot/guilds/$guildId/backups': typeof ApiBotGuildsGuildIdBackupsRoute
  '/api/bot/guilds/$guildId/config': typeof ApiBotGuildsGuildIdConfigRoute
  '/api/public/bot/config/$guildId': typeof ApiPublicBotConfigGuildIdRoute
  '/api/public/bot/verified-members/$guildId': typeof ApiPublicBotVerifiedMembersGuildIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/legal': typeof LegalRoute
  '/pricing': typeof PricingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/_authenticated/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/discord': typeof ApiAuthDiscordRoute
  '/api/auth/discord-guilds': typeof ApiAuthDiscordGuildsRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/servers/$guildId': typeof AuthenticatedDashboardServersGuildIdRoute
  '/api/bot/status/$guildId': typeof ApiBotStatusGuildIdRoute
  '/api/public/bot/backup': typeof ApiPublicBotBackupRoute
  '/api/public/verify/$token': typeof ApiPublicVerifyTokenRoute
  '/_authenticated/dashboard/servers/': typeof AuthenticatedDashboardServersIndexRoute
  '/api/bot/guilds/$guildId/backups': typeof ApiBotGuildsGuildIdBackupsRoute
  '/api/bot/guilds/$guildId/config': typeof ApiBotGuildsGuildIdConfigRoute
  '/api/public/bot/config/$guildId': typeof ApiPublicBotConfigGuildIdRoute
  '/api/public/bot/verified-members/$guildId': typeof ApiPublicBotVerifiedMembersGuildIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/docs'
    | '/features'
    | '/legal'
    | '/pricing'
    | '/dashboard'
    | '/auth/callback'
    | '/verify/$token'
    | '/dashboard/billing'
    | '/api/auth/callback'
    | '/api/auth/discord'
    | '/api/auth/discord-guilds'
    | '/api/auth/session'
    | '/api/auth/signout'
    | '/dashboard/'
    | '/dashboard/servers/$guildId'
    | '/api/bot/status/$guildId'
    | '/api/public/bot/backup'
    | '/api/public/verify/$token'
    | '/dashboard/servers/'
    | '/api/bot/guilds/$guildId/backups'
    | '/api/bot/guilds/$guildId/config'
    | '/api/public/bot/config/$guildId'
    | '/api/public/bot/verified-members/$guildId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/docs'
    | '/features'
    | '/legal'
    | '/pricing'
    | '/auth/callback'
    | '/verify/$token'
    | '/dashboard/billing'
    | '/api/auth/callback'
    | '/api/auth/discord'
    | '/api/auth/discord-guilds'
    | '/api/auth/session'
    | '/api/auth/signout'
    | '/dashboard'
    | '/dashboard/servers/$guildId'
    | '/api/bot/status/$guildId'
    | '/api/public/bot/backup'
    | '/api/public/verify/$token'
    | '/dashboard/servers'
    | '/api/bot/guilds/$guildId/backups'
    | '/api/bot/guilds/$guildId/config'
    | '/api/public/bot/config/$guildId'
    | '/api/public/bot/verified-members/$guildId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/docs'
    | '/features'
    | '/legal'
    | '/pricing'
    | '/_authenticated/dashboard'
    | '/auth/callback'
    | '/verify/$token'
    | '/_authenticated/dashboard/billing'
    | '/api/auth/callback'
    | '/api/auth/discord'
    | '/api/auth/discord-guilds'
    | '/api/auth/session'
    | '/api/auth/signout'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/servers/$guildId'
    | '/api/bot/status/$guildId'
    | '/api/public/bot/backup'
    | '/api/public/verify/$token'
    | '/_authenticated/dashboard/servers/'
    | '/api/bot/guilds/$guildId/backups'
    | '/api/bot/guilds/$guildId/config'
    | '/api/public/bot/config/$guildId'
    | '/api/public/bot/verified-members/$guildId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DocsRoute: typeof DocsRoute
  FeaturesRoute: typeof FeaturesRoute
  LegalRoute: typeof LegalRoute
  PricingRoute: typeof PricingRoute
  VerifyTokenRoute: typeof VerifyTokenRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthDiscordRoute: typeof ApiAuthDiscordRoute
  ApiAuthDiscordGuildsRoute: typeof ApiAuthDiscordGuildsRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthSignoutRoute: typeof ApiAuthSignoutRoute
  ApiBotStatusGuildIdRoute: typeof ApiBotStatusGuildIdRoute
  ApiPublicBotBackupRoute: typeof ApiPublicBotBackupRoute
  ApiPublicVerifyTokenRoute: typeof ApiPublicVerifyTokenRoute
  ApiBotGuildsGuildIdBackupsRoute: typeof ApiBotGuildsGuildIdBackupsRoute
  ApiBotGuildsGuildIdConfigRoute: typeof ApiBotGuildsGuildIdConfigRoute
  ApiPublicBotConfigGuildIdRoute: typeof ApiPublicBotConfigGuildIdRoute
  ApiPublicBotVerifiedMembersGuildIdRoute: typeof ApiPublicBotVerifiedMembersGuildIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/auth/signout': {
      id: '/api/auth/signout'
      path: '/api/auth/signout'
      fullPath: '/api/auth/signout'
      preLoaderRoute: typeof ApiAuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord-guilds': {
      id: '/api/auth/discord-guilds'
      path: '/api/auth/discord-guilds'
      fullPath: '/api/auth/discord-guilds'
      preLoaderRoute: typeof ApiAuthDiscordGuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord': {
      id: '/api/auth/discord'
      path: '/api/auth/discord'
      fullPath: '/api/auth/discord'
      preLoaderRoute: typeof ApiAuthDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/billing': {
      id: '/_authenticated/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AuthenticatedDashboardBillingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/servers/': {
      id: '/_authenticated/dashboard/servers/'
      path: '/servers'
      fullPath: '/dashboard/servers/'
      preLoaderRoute: typeof AuthenticatedDashboardServersIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/verify/$token': {
      id: '/api/public/verify/$token'
      path: '/api/public/verify/$token'
      fullPath: '/api/public/verify/$token'
      preLoaderRoute: typeof ApiPublicVerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/backup': {
      id: '/api/public/bot/backup'
      path: '/api/public/bot/backup'
      fullPath: '/api/public/bot/backup'
      preLoaderRoute: typeof ApiPublicBotBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot/status/$guildId': {
      id: '/api/bot/status/$guildId'
      path: '/api/bot/status/$guildId'
      fullPath: '/api/bot/status/$guildId'
      preLoaderRoute: typeof ApiBotStatusGuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/servers/$guildId': {
      id: '/_authenticated/dashboard/servers/$guildId'
      path: '/servers/$guildId'
      fullPath: '/dashboard/servers/$guildId'
      preLoaderRoute: typeof AuthenticatedDashboardServersGuildIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/bot/verified-members/$guildId': {
      id: '/api/public/bot/verified-members/$guildId'
      path: '/api/public/bot/verified-members/$guildId'
      fullPath: '/api/public/bot/verified-members/$guildId'
      preLoaderRoute: typeof ApiPublicBotVerifiedMembersGuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/config/$guildId': {
      id: '/api/public/bot/config/$guildId'
      path: '/api/public/bot/config/$guildId'
      fullPath: '/api/public/bot/config/$guildId'
      preLoaderRoute: typeof ApiPublicBotConfigGuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot/guilds/$guildId/config': {
      id: '/api/bot/guilds/$guildId/config'
      path: '/api/bot/guilds/$guildId/config'
      fullPath: '/api/bot/guilds/$guildId/config'
      preLoaderRoute: typeof ApiBotGuildsGuildIdConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot/guilds/$guildId/backups': {
      id: '/api/bot/guilds/$guildId/backups'
      path: '/api/bot/guilds/$guildId/backups'
      fullPath: '/api/bot/guilds/$guildId/backups'
      preLoaderRoute: typeof ApiBotGuildsGuildIdBackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardBillingRoute: typeof AuthenticatedDashboardBillingRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardServersGuildIdRoute: typeof AuthenticatedDashboardServersGuildIdRoute
  AuthenticatedDashboardServersIndexRoute: typeof AuthenticatedDashboardServersIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardBillingRoute: AuthenticatedDashboardBillingRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardServersGuildIdRoute:
      AuthenticatedDashboardServersGuildIdRoute,
    AuthenticatedDashboardServersIndexRoute:
      AuthenticatedDashboardServersIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DocsRoute: DocsRoute,
  FeaturesRoute: FeaturesRoute,
  LegalRoute: LegalRoute,
  PricingRoute: PricingRoute,
  VerifyTokenRoute: VerifyTokenRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthDiscordRoute: ApiAuthDiscordRoute,
  ApiAuthDiscordGuildsRoute: ApiAuthDiscordGuildsRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthSignoutRoute: ApiAuthSignoutRoute,
  ApiBotStatusGuildIdRoute: ApiBotStatusGuildIdRoute,
  ApiPublicBotBackupRoute: ApiPublicBotBackupRoute,
  ApiPublicVerifyTokenRoute: ApiPublicVerifyTokenRoute,
  ApiBotGuildsGuildIdBackupsRoute: ApiBotGuildsGuildIdBackupsRoute,
  ApiBotGuildsGuildIdConfigRoute: ApiBotGuildsGuildIdConfigRoute,
  ApiPublicBotConfigGuildIdRoute: ApiPublicBotConfigGuildIdRoute,
  ApiPublicBotVerifiedMembersGuildIdRoute:
    ApiPublicBotVerifiedMembersGuildIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
